### ISSUE TITLE
Create a setup wizard view

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/DriveTransfer#16]
This view will guide users through setting up a transfer.

**Comment by j-rewerts** [comment]
- [ ] Resolve #13 Add a file picker
- [ ] Resolve #17 Pulls ueser's emails
- [ ] Resolve #11 Initiate transfer

**Comment by j-rewerts** [comment]
I'll consider this closed, since the log view is done. User emails will come later.
